name: Create GitHub Release

on:
  push:
    tags:
      - "v*-sv"

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          # "latest", "nightly", or a semver
          version: "~> v2"
          args: release --skip=publish --clean

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: "dist/*.deb"
          omitBody: "true"
          token: ${{ secrets.GITHUB_TOKEN }}
